name: 'PROYECTO_DE58'
version: '1.0.0'
config-version: 2

profile: 'PROYECTO_DE58'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  
      #Comiendo de la declaración de los modelos que tengo en mi proyecto en el entorno DEV
models:
  PROYECTO_DE58:
    staging:
      +materialized: view
      +schema: STAGING
      +database: "{{ 'DEV_SILVER_DB' if target.name == 'dev' else 'PRO_SILVER_DB' }}"

    marts:
      +materialized: table
      +schema: MARTS
      +database: "{{ 'DEV_GOLD_DB' if target.name == 'dev' else 'PRO_GOLD_DB' }}"