name: 'PROYECTO_DE58'
version: '1.0.0'
config-version: 2

profile: 'PROYECTO_DE58'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
 
clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------------------------
# HOOKS — Control de warehouse y sesión
# Se ejecutan al inicio y fin de CADA job automáticamente
# ---------------------------------------------------------------------------
on-run-start:
  - "ALTER WAREHOUSE {{ target.warehouse }} RESUME IF SUSPENDED"
  - "ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300"

on-run-end:
  - "ALTER WAREHOUSE {{ target.warehouse }} SUSPEND"

# ---------------------------------------------------------------------------
# COMIENZO DE MODELS:
# ---------------------------------------------------------------------------

models:
  PROYECTO_DE58:
    staging:
      +materialized: view
      +schema: STAGING
      +database: "{{ env_var('DBT_ENVIRONMENT') }}_SILVER_DB"

    marts:
      +materialized: table
      +schema: MARTS
      +database: "{{ env_var('DBT_ENVIRONMENT') }}_GOLD_DB"